---
- name: Install python3 pip
  apt:
    name: python3-pip

- name: Install Web3py
  pip:
    name: web3
    executable: pip3

- name: Delete former geth service file
  file: 
    path: /etc/systemd/system/geth.service
    state: absent

# change the path when time to refactor
- name: Put new geth service file
  template:
    src: roles/eth_geth/templates/geth.service.j2
    dest: /etc/systemd/system/geth.service
    owner: root
    group: root
    mode: 0644
  vars:
    - activate_mining: true
    - account_address: "{{account_addresses_list.stdout_lines[0]}}"

- name: reload systemd
  command: systemctl daemon-reload

- name: enable geth service
  service: name=geth state=restarted

- name: Copy the transactions generation script
  copy:
    src: roles/eth_geth/files/generate_transactions.py
    dest: /tmp/generate_transactions.py

- name: Copy the transactions generation script service
  copy:
    src: roles/eth_geth/files/generate_transactions.service
    dest: /etc/systemd/system/generate_transactions.service

- name: activate the transactions generation script service
  service: name=generate_transactions enabled=yes state=started