---
- name: list accounts
  shell: geth --datadir /tmp/home/geth/.ethereum/ -verbosity 0 account list | grep -Po 'Account \#[0-9]+:\ {\K([a-zA-Z0-9]+)'
  register: account_addresses_list
  ignore_errors: yes

- name: Verify account addresses list
  debug:
    msg: "{{ account_addresses_list.stdout_lines }}"

- name: Put genesis file
  template:
    src: roles/eth_geth_clique/templates/genesis.json.j2
    dest: /tmp/home/geth/genesis.json
    owner: geth
    mode: u=rwx,g=rwx,o=rwx
  vars:
    add_accounts: true

- name: Stop geth service
  service: name=geth state=stopped

- name: Delete former chain
  file:
    path: /tmp/home/geth/.ethereum/geth/chaindata/
    state: absent

- name: Init geth
  shell: geth --config /tmp/home/geth/config.toml init /tmp/home/geth/genesis.json
  become: yes
  become_user: geth

- name: Start geth service
  service: name=geth state=started
