- name: Check installed parity version
  shell: parity --version | grep 'version Parity' | sed -n -E -e 's/.*\/(v[0-9]+\.[0-9]+\.[0-9]+).*/\1/p'
  register: parity_version
  ignore_errors: yes
  failed_when: false
  changed_when: false
  check_mode: no

- set_fact: parity_installed={{ parity_version.stdout_lines[0] is defined }}

- name: Install parity client
  include: install_client.yml
  when: not parity_installed