- name: Check installed parity version
  shell: parity --version | grep 'version Parity' | sed -n -E -e 's/.*\/(v[0-9]+\.[0-9]+\.[0-9]+).*/\1/p'
  register: parity_version
  ignore_errors: yes
  failed_when: false
  changed_when: false
  check_mode: no

- set_fact: parity_installed={{ parity_version.stdout_lines[0] is defined }}

- name: Install parity client
  include: install_client.yml
  when: not parity_installed

- name: Retrieve Enode
  shell: >
    curl
    --data '{"method":"parity_enode","params":[],"id":1,"jsonrpc":"2.0"}' 
    -H "Content-Type:application/json" 
    -X POST http://127.0.0.1:8545 | sed -n 's/.*\(enode.*\)@.*/\1/p'
  register: enode
  until: enode.stdout is match("enode://[a-zA-Z0-9]+")
  retries: 10 
  delay: 5
  command_warning: false

- debug: msg={{enode.stdout}}@{{ansible_default_ipv4.address}}:30303