- group: name={{ parity_group }} system=yes state=present
- user: name={{ parity_user }} group={{ parity_group }} home={{ parity_home }} state=present

- name: Download Parity installer
  get_url: 
    url: "{{ parity_installer_url }}"
    dest: /tmp/parity_installer.sh

- name: Make Parity installer executable
  file:
    dest: /tmp/parity_installer.sh
    mode: a+x

- name: Run Parity installer
  shell: /tmp/parity_installer.sh

- name: configuration file for systemd parity service
  template:
    src: templates/parity.service.j2
    dest: /etc/systemd/system/parity.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd

- name: enable parity service
  service: name=parity enabled=yes state=started