---
-   hosts: all
    tasks:
    -   name: List all key files
        shell: (cd /tmp/home/geth/.ethereum/keystore; find . -maxdepth 1 -type f) | cut -d'/' -f2
        register: files_to_copy

    -   fetch:
          src: /tmp/home/geth/.ethereum/keystore/{{ item }}
          dest: /tmp/BCTMARK/
          flat: yes
        with_items: "{{ files_to_copy.stdout_lines }}"