- name: Check installed geth version
  shell: >
    geth --verbosity 0 version | grep Version | sed -nEe 's/^Version:\ ([0-9]+\.[0-9]+\.[0-9]+-[a-zA-Z]+)/\1/p'
  register: geth_version
  ignore_errors: yes
  failed_when: false
  changed_when: false
  check_mode: no

- name: Install geth client
  include: utils/install_client.yml